version: "3"

services:
    match:
        image: "fleet/matchsvr:latest"
        ports:
         - "8000:8000"
        restart: always
        networks:
            int:
                aliases:
                 - match
    game01:
        image: "fleet/httpsvr:latest"
        ports:
         - "8001:8000"
        restart: always
        networks:
            int:
                aliases:
                 - game01
    game02:
        image: "fleet/httpsvr:latest"
        ports:
         - "8002:8000"
        restart: always
        networks:
            int:
                aliases:
                 - game02
    game03:
        image: "fleet/httpsvr:latest"
        ports:
         - "8003:8000"
        restart: always
        networks:
            int:
                aliases:
                 - game03
    game04:
        image: "fleet/httpsvr:latest"
        ports:
         - "8004:8000"
        restart: always
        networks:
            int:
                aliases:
                 - game04
    game05:
        image: "fleet/httpsvr:latest"
        ports:
         - "8005:8000"
        restart: always
        networks:
            int:
                aliases:
                 - game05
    game06:
        image: "fleet/httpsvr:latest"
        ports:
         - "8006:8000"
        restart: always
        networks:
            int:
                aliases:
                 - game06
    game07:
        image: "fleet/httpsvr:latest"
        ports:
         - "8007:8000"
        restart: always
        networks:
            int:
                aliases:
                 - game07
    game08:
        image: "fleet/httpsvr:latest"
        ports:
         - "8008:8000"
        restart: always
        networks:
            int:
                aliases:
                 - game08
    game09:
        image: "fleet/httpsvr:latest"
        ports:
         - "8009:8000"
        restart: always
        networks:
            int:
                aliases:
                 - game09

networks:
    int:
        driver: bridge

